config/routes.rb
Feeddemo::Application.routes.draw do

  resources :rss_feeds

  resources :feeds

  match '/feed_url' => 'rss_feeds#feed_url', :as => :feed_url
  match '/create_feed_url' => 'rss_feeds#create_feed_url', :as => :create_feed_url
  match '/del_feed_url' => 'rss_feeds#del_feed_url', :as => :del_feed_url
  
  
  

  root :to => 'rss_feeds#feed_url'

end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
  attr_accessible :content, :guid, :name, :published_at, :url
  
   require 'feedjira'

  def self.update_from_feed(feed_url)
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    add_entries(feed.entries) if feed && feed.entries
  end

  def self.update_from_feed_continuously(feed_url, delay_interval = 1.minutes)
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    add_entries(feed.entries)
    loop do
      sleep delay_interval.to_i
      feed = Feedjira::Feed.update(feed)
      add_entries(feed.new_entries) if feed.updated?
    end
  end

  private
  def self.add_entries(entries)
    entries.each do |entry|
      unless exists? :guid => entry.id
        create!(
            :name         => entry.title,
            :content      => entry.summary,
            :url          => entry.url,
            :published_at => entry.published,
            :guid         => entry.id
        )
      end
    end
  end
  
  
end

app/models/rss_feed_url.rb
class RssFeedUrl < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  
  
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  # GET /rss_feeds
  # GET /rss_feeds.json


  require 'feedjira'

  def index
    
    if !params[:feed_url].blank?
      feed = RssFeed.update_from_feed("#{params[:feed_url]}")
    else
      feed = RssFeed.update_from_feed("http://news.google.com/?output=rss")
    end    
    
    @rss_feeds = RssFeed.order('published_at ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rss_feeds }
    end
  end

 
  # GET /rss_feeds/1/edit
  def edit
    @rss_feed = RssFeed.find(params[:id])
  end

  # POST /rss_feeds
  # POST /rss_feeds.json
  
  def create
    @rss_feed = RssFeed.new(params[:rss_feed])

    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully created.' }
        format.json { render json: @rss_feed, status: :created, location: @rss_feed }
      else
        format.html { render action: "new" }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rss_feeds/1
  # PUT /rss_feeds/1.json
  def update
    @rss_feed = RssFeed.find(params[:id])

    respond_to do |format|
      if @rss_feed.update_attributes(params[:rss_feed])
        format.html { redirect_to '/', notice: 'Rss feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.json
  def destroy
    @rss_feed = RssFeed.find(params[:id])
    @rss_feed.destroy

    respond_to do |format|
      format.html { redirect_to rss_feeds_url }
      format.json { head :no_content }
    end
  end
  
  
  def feed_url   
    @rss_feed_urls = RssFeedUrl.all

  end
  
  def create_feed_url
    @rss_feed_url = RssFeedUrl.new(params[:rss_feed_url])
   
    logger.info "sssssssssssssssssssss #{params[:rss_feed_url].inspect}"
    respond_to do |format|
      if @rss_feed_url.save
        format.html { redirect_to feed_url_path, notice: 'Rss feed URL was successfully created.' }
        format.json { render json: @rss_feed_urls, status: :created, location: @rss_feed_urls }
      else
        format.html { render action: "feed_url" }
        format.json { render json: @rss_feed_urls.errors, status: :unprocessable_entity }
      end
    end
    
    
  end



  def del_feed_url
    @rss_feed_url = RssFeedUrl.find(params[:id])

    if @rss_feed_url.destroy
      respond_to do |format|
        format.html { redirect_to feed_url_path, notice: 'Rss url is removed' }
        format.json { head :no_content }
      end
    end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Feeddemo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Feeddemo</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Feeds", "/rss_feeds"  %></li>


            </ul>




          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Feeds", "/rss_feeds"  %></li>
              <li><%= link_to "Feed Url", "/rss_feeds/feed_url"  %></li>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/rss_feeds/_form.html.erb
<%= form_for(@rss_feed) do |f| %> 

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :value => (@rss_feed.content.html_safe) %>
  </div>
  <div class="field">
    <%= f.label :guid %><br />
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rss_feeds/edit.html.erb
<%= render 'form' %>

app/views/rss_feeds/feed_url.html.erb
<%= form_tag create_feed_url_path do %>
  <table>
    <tr>
      <td>Add Feed Url</td>
      <td><input type="text" name="rss_feed_url[url]" /></td>
      <td><input type="submit" value="Add Url" /></td>
    </tr>
  </table>
<% end %>





<table class="table table-striped">
  <thead>
  <th>URL</th>
  <th>Action</th>
</thead>

<tbody>
<% rss_feeds = RssFeedUrl.all  %>
  <% rss_feeds.each do |rss_feed| %>
    <tr>
      <td>
        <%= link_to  "#{rss_feed.url}", :controller => 'rss_feeds' , :action => 'index' , :feed_url => rss_feed.url %>
      </td>
      <td><%= link_to 'Edit' %></td>
      <td><%= link_to 'Destroy', :controller => 'rss_feeds', :action => 'del_feed_url', :id => rss_feed.id %></td>

    </tr>
  <% end if rss_feeds %>
</tbody>
</table>

app/views/rss_feeds/index.html.erb
<table class="table table-striped">
  <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Action</th>
  </thead>

  <tbody>
  <% @rss_feeds.each do |rss_feed|%>
      <tr>
        <td><%= rss_feed.id %></td>
        <td>
          <%= link_to "#{rss_feed.name}", "#{rss_feed.url}",:target => "_blank" %>
        </td>
        <td><%= link_to 'Edit', edit_rss_feed_path(rss_feed) %></td>
        <td><%= link_to 'Destroy', rss_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>